#Written by Taydeo. Adjusted by IronDragoon
- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 18000
  - !type:DepartmentTimeRequirement
    department: Security
    time: 7200
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External

- type: startingGear
  id: BrigmedicGear
  equipment:
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - Syringe
    - Flash
